### ISSUE TITLE
Yuv.toMat crashed

### ISSUE THREAD

**Issue by shimrik** [quickbirdstudios/yuvToMat#1]
The toMat throws this:
java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.core.Mat.n_Mat(int, int, int, java.nio.ByteBuffer) (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__IIILjava_nio_ByteBuffer_2).
The Image given to the function is an ArImage from google's ARCore.
Any ideas why it happens and how to fix it?
Thank you!

**Comment by sellmair** [comment]
Hey @shimrik, 
thanks for reporting! We are releasing a version 1.0 soon, that should fix this problem ☺️

**Comment by sellmair** [comment]
We recently uploaded version 1.1.0 of this library 🎊 
Could you please check if this issue still exists for you?

https://github.com/quickbirdstudios/yuvToMat/releases/tag/v1.1.0

**Comment by zzxjl1** [comment]
issue still exists
`E/m.app.toomucha: No implementation found for long org.opencv.core.Mat.n_Mat(int, int, int, java.nio.ByteBuffer) (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__IIILjava_nio_ByteBuffer_2)
E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
    Process: com.app.toomuchai, PID: 7145
    java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.core.Mat.n_Mat(int, int, int, java.nio.ByteBuffer) (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__IIILjava_nio_ByteBuffer_2)
        at org.opencv.core.Mat.n_Mat(Native Method)
        at org.opencv.core.Mat.<init>(Mat.java:52)
        at com.quickbirdstudios.yuv2mat.YuvN12Image.toRgb(YuvN12Image.kt:97)
        at com.quickbirdstudios.yuv2mat.Image_toMatKt.rgb(Image+toMat.kt:20)
        at com.quickbirdstudios.yuv2mat.Yuv$Companion.rgb(Yuv.kt:57)
        at com.quickbirdstudios.yuv2mat.Yuv.rgb(Unknown Source:2)
        at com.app.toomuchai.CameraServiceold$4.run(CameraServiceold.java:195)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by sellmair** [comment]
Could you provide us some sample code to reproduce this issue?

**Comment by zzxjl1** [comment]
https://drive.google.com/file/d/1LYvGoKy5ldHu-gqfPy0d6_ZzeBk3U2qE/view?usp=sharing

**Comment by zzxjl1** [comment]
’
private BaseLoaderCallback mLoaderCallback = new BaseLoaderCallback(this) {
        @Override
        public void onManagerConnected(int status) {
            switch (status) {
                case LoaderCallbackInterface.SUCCESS:
                {
                    Log.i(TAG, "OpenCV loaded successfully");
                    mOpenCvCameraView.enableView();
                } break;
                default:
                {
                    super.onManagerConnected(status);
                } break;
            }
        }
    };

 @Override
    public void onResume()
    {
        super.onResume();
        if (!OpenCVLoader.initDebug()) {
            Log.d(TAG, "Internal OpenCV library not found. Using OpenCV Manager for initialization");
            OpenCVLoader.initAsync(OpenCVLoader.OPENCV_VERSION_3_0_0, this, mLoaderCallback);
        } else {
            Log.d(TAG, "OpenCV library found inside package. Using it!");
            mLoaderCallback.onManagerConnected(LoaderCallbackInterface.SUCCESS);
        }
    }
‘
problem solved after adding these lines
